name: Salesforce Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Salesforce CLI
      run: npm install -g @salesforce/cli

    - name: Authenticate to Salesforce
      run: |
        echo "${{ secrets.SALESFORCE_AUTH_URL }}" > auth.txt
        sf org login sfdx-url --sfdx-url-file auth.txt --alias dev-org
        rm auth.txt

    - name: Deploy to Salesforce
      run: |
        echo "🚀 Deploying to Salesforce..."
        sf project deploy start --target-org dev-org
        echo "✅ Deployment completed!"

    - name: Run tests
      run: |
        echo "🧪 Running tests..."
        sf apex run test --target-org dev-org --result-format human